name: Ap-finance CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: localhost
      PORT: 27017
      PG_DB: Finance
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: |
          cd ./docker
          docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Check running containers
        run: docker ps -a
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          cd ./server
          ./gradlew build
